# ✅ BASELINE MODEL
# 🤖 ML & 🧹 PREPROCESSING

In [15]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, 
    confusion_matrix,
    roc_auc_score
)
from joblib import dump
import warnings
warnings.filterwarnings('ignore')

# MAKE PLOTS LOOK NICE
sns.set_theme(style='whitegrid', palette='muted')
plt.rcParams['figure.dpi'] = 110
print('✅ All Libraries Imported Successfully!')

✅ All Libraries Imported Successfully!

# 📂 LOADED DATASET

In [16]:
df = pd.read_csv('../movie_genre_classification_final.csv')
print('\n')
print(f'📐 Dataset Shape: {df.shape[0]:,} rows x {df.shape[1]} columns')
print('\n')
df.head()

📐 Dataset Shape: 50,000 rows x 17 columns

,Title,Year,Director,Duration,Rating,Votes,Description,Language,Country,Budget_USD,BoxOffice_USD,Genre,Production_Company,Content_Rating,Lead_Actor,Num_Awards,Critic_Reviews
0,Winds of Fate 4,1980,R. Lee,167,4.1,182425,A touching love story with heartwarming moments.,Spanish,China,39979615,179936008,Romance,DreamWorks,R,Kangana Ranaut,8,229
1,Firestorm 11,2014,S. Chen,166,4.1,449351,A fast-paced thriller with intense action scenes.,Korean,China,116404774,802121619,Action,Netflix,R,Kangana Ranaut,20,466
2,Silent Echo 2,2016,A. Khan,170,4.1,363328,A fast-paced thriller with intense action scenes.,Korean,Japan,166261330,225526871,Action,Pixar,PG,Amitabh Bachchan,16,539
3,City Lights 4,1982,L. Zhang,170,9.9,62371,An emotional journey exploring complex charact...,Japanese,Japan,28861315,69813738,Drama,Netflix,NC-17,Natalie Portman,15,606
4,Broken Truth 1,1990,L. Zhang,91,5.3,4600,An imaginative world filled with magic and won...,Korean,USA,43890403,375136716,Fantasy,Studio Ghibli,PG,Chris Evans,6,330

In [17]:
df.tail()

,Title,Year,Director,Duration,Rating,Votes,Description,Language,Country,Budget_USD,BoxOffice_USD,Genre,Production_Company,Content_Rating,Lead_Actor,Num_Awards,Critic_Reviews
49995,Ocean Call 20,2013,T. Johnson,149,6.8,340904,A touching love story with heartwarming moments.,English,UK,62456512,3291117,Romance,Yash Raj Films,PG-13,Leonardo DiCaprio,18,481
49996,Ocean Call 13,2001,M. Brown,166,7.6,214228,A spine-chilling tale that evokes fear and dread.,Japanese,South Korea,33239921,465759764,Horror,Netflix,PG-13,Emma Watson,3,84
49997,Last Mission 15,2017,J. Smith,158,9.2,251931,A light-hearted comedy that guarantees laughter.,Korean,South Korea,79589169,820566917,Comedy,Paramount Pictures,PG-13,Shah Rukh Khan,1,994
49998,Firestorm 11,1992,J. Smith,166,7.2,487956,A spine-chilling tale that evokes fear and dread.,Mandarin,South Korea,179834680,131779818,Horror,Amazon Studios,R,Kangana Ranaut,10,349
49999,Silent Echo 12,2009,P. Adams,117,4.3,392762,An imaginative world filled with magic and won...,Spanish,France,45434366,957562425,Fantasy,Sony Pictures,PG-13,Emma Watson,20,191

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               50000 non-null  str
 1   Year                50000 non-null  int64
 2   Director            50000 non-null  str
 3   Duration            50000 non-null  int64
 4   Rating              50000 non-null  float64
 5   Votes               50000 non-null  int64
 6   Description         50000 non-null  str
 7   Language            50000 non-null  str
 8   Country             50000 non-null  str
 9   Budget_USD          50000 non-null  int64
 10  BoxOffice_USD       50000 non-null  int64
 11  Genre               50000 non-null  str
 12  Production_Company  50000 non-null  str
 13  Content_Rating      50000 non-null  str
 14  Lead_Actor          50000 non-null  str
 15  Num_Awards          50000 non-null  int64
 16  Critic_Reviews      50000 non-null  int64
dtypes: float64(1), int64(7), str(9)
memory usage: 6.5 MB

In [19]:
df.columns  # shows the columns

Index(['Title', 'Year', 'Director', 'Duration', 'Rating', 'Votes',
       'Description', 'Language', 'Country', 'Budget_USD', 'BoxOffice_USD',
       'Genre', 'Production_Company', 'Content_Rating', 'Lead_Actor',
       'Num_Awards', 'Critic_Reviews'],
      dtype='str')

In [20]:
df.nunique()  # shows how many unique elements have for each column

Title                   260
Year                     44
Director                 10
Duration                101
Rating                   60
Votes                 47579
Description               7
Language                  7
Country                   7
Budget_USD              100
BoxOffice_USD           100
Genre                     7
Production_Company       10
Content_Rating            5
Lead_Actor               10
Num_Awards               21
Critic_Reviews         1001
dtype: int64

In [21]:
df.describe()

,Year,Duration,Rating,Votes,Budget_USD,BoxOffice_USD,Num_Awards,Critic_Reviews
count,50000.000000,50000.00000,50000.000000,50000.000000,5.000000e+04,5.000000e+04,50000.000000,50000.000000
mean,2001.562620,130.07312,6.926472,249699.050540,9.179143e+07,5.176063e+08,9.964440,500.176380
std,12.722539,29.11097,1.698758,144314.043032,5.823888e+07,2.880283e+08,6.066303,289.971792
min,1980.000000,80.00000,4.000000,516.000000,1.135566e+06,3.291117e+06,0.000000,0.000000
25%,1991.000000,105.00000,5.500000,124531.500000,4.389040e+07,2.590329e+08,5.000000,248.000000
50%,2002.000000,130.00000,6.900000,248582.000000,8.062480e+07,5.109973e+08,10.000000,500.000000
75%,2013.000000,155.00000,8.400000,374833.500000,1.475557e+08,7.704129e+08,15.000000,751.000000
max,2023.000000,180.00000,9.900000,499984.000000,1.984445e+08,9.925159e+08,20.000000,1000.000000

# 🧹 CLEAN THE DATA

In [22]:
df.isnull().sum()

Title                 0
Year                  0
Director              0
Duration              0
Rating                0
Votes                 0
Description           0
Language              0
Country               0
Budget_USD            0
BoxOffice_USD         0
Genre                 0
Production_Company    0
Content_Rating        0
Lead_Actor            0
Num_Awards            0
Critic_Reviews        0
dtype: int64

# 🛠️ DATA PREPROCESSING

In [23]:
# Separate features and target
TARGET = 'Genre'

# Make a copy, so we don't need to change the orginal DataFrame
df_movie = df.copy()

# Encode target separately so we can decode later
le_target = LabelEncoder()
df_movie[TARGET] = le_target.fit_transform(df_movie[TARGET])
print(f"\nTarget classes: {list(le_target.classes_)}")
print("✅ Encoding done!")

Target classes: ['Action', 'Comedy', 'Drama', 'Fantasy', 'Horror', 'Romance', 'Thriller']
✅ Encoding done!

# ✂️ SPLIT THE DATASET INTO: X_train and X_test

In [24]:

import sys
import os
from sklearn.model_selection import train_test_split
sys.path.append(os.path.abspath(".."))
from src.preprocessing_dataset import DataPreprocessor




X = df_movie.drop("Genre", axis=1)
y = df_movie["Genre"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=9
)

preprpcessor = DataPreprocessor()
preprpcessor.find_columns(X_train)

X_train_enc, X_test_enc = preprpcessor.encode(
    X_train,
    X_test
)
X_train_scaled, X_test_scaled = preprpcessor.scale(
    X_train_enc,
    X_test_enc
)